/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.2/userguide/building_java_projects.html in the Gradle documentation.
 */

import org.gradle.testing.jacoco.plugins.JacocoPluginExtension

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
    id("jacoco")
}

// Configure JaCoCo extension explicitly to avoid unresolved reference in static analysis
extensions.configure<JacocoPluginExtension> {
    toolVersion = "0.8.11"
}

project.version = "1.2.0"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform)
    testRuntimeOnly(libs.junit.vintage.engine)

    // Testing dependencies
    testImplementation(libs.concordion)
    
    // Mockito for minimal mocking
    testImplementation("org.mockito:mockito-core:5.8.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.8.0")
    
    // AssertJ for fluent assertions
    testImplementation("org.assertj:assertj-core:3.25.1")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)

    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.test {
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)

    systemProperty("concordion.output.dir", "${project.layout.buildDirectory.get().asFile}/reports/concordion")

    doFirst {
        layout.buildDirectory.dir("reports/concordion").get().asFile.mkdirs()
    }
}

// Custom task to run only Concordion tests
tasks.register("concordionTest", Test::class) {
    useJUnitPlatform {
        includeTags("concordion")
    }
    
    systemProperty("concordion.output.dir", layout.buildDirectory.dir("reports/concordion").get().asFile.absolutePath)
    
    doFirst {
        layout.buildDirectory.dir("reports/concordion").get().asFile.mkdirs()
    }
    
    finalizedBy("jacocoTestReport")
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(true)
        html.required.set(true)
        html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco/test"))
    }
}

tasks.jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = "0.80".toBigDecimal()
            }
        }
    }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "org.makechtec.xihucalli"
            artifactId = "password_generator"
            version = project.version.toString()

            from(components["java"])
        }
    }

    repositories {
        maven {
            url = uri("https://makech-technology-879381274336.d.codeartifact.us-east-2.amazonaws.com/maven/makech-technology-maven-repository/")
            credentials {
                username = "aws"
                password = System.getenv("CODEARTIFACT_AUTH_TOKEN")
            }
        }
    }
}