/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.2/userguide/building_java_projects.html in the Gradle documentation.
 */

import org.gradle.testing.jacoco.tasks.JacocoReport
import org.gradle.testing.jacoco.plugins.JacocoPluginExtension

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
    id("jacoco")
}

// Configure JaCoCo extension explicitly to avoid unresolved reference in static analysis
extensions.configure<JacocoPluginExtension> {
    toolVersion = "0.8.10"
}

project.version = "1.2.0"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)

    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    // Ensure report task runs after tests
    finalizedBy("jacocoTestReport")
}

// Replace unconditional registration with a guarded configuration so we don't register the task twice
val existingJacoco = tasks.findByName("jacocoTestReport") as? JacocoReport
if (existingJacoco == null) {
    tasks.register<JacocoReport>("jacocoTestReport") {
        dependsOn(tasks.named("test"))

        reports {
            xml.required.set(true)
            html.required.set(true)
            csv.required.set(false)
        }

        // Adjust paths if your sources/classes are in different locations
        val mainSrc = "src/main/java"
        classDirectories.setFrom(fileTree("${buildDir}/classes/java/main") {
            // exclude generated or irrelevant classes if needed
            exclude("**/R.class", """**/R${'$'}*.class""", """**/*${'$'}ViewInjector*.*""")
        })
        sourceDirectories.setFrom(files(mainSrc))
        executionData.setFrom(fileTree(buildDir).include("**/jacoco/*.exec", "**/*.exec"))
    }
} else {
    existingJacoco.apply {
        dependsOn(tasks.named("test"))
        reports {
            xml.required.set(true)
            html.required.set(true)
            csv.required.set(false)
        }
        val mainSrc = "src/main/java"
        classDirectories.setFrom(fileTree("${buildDir}/classes/java/main") {
            exclude("**/R.class", """**/R${'$'}*.class""", """**/*${'$'}ViewInjector*.*""")
        })
        sourceDirectories.setFrom(files(mainSrc))
        executionData.setFrom(fileTree(buildDir).include("**/jacoco/*.exec", "**/*.exec"))
    }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "org.makechtec.xihucalli"
            artifactId = "password_generator"
            version = project.version.toString()

            from(components["java"])
        }
    }

    repositories {
        maven {
            url = uri("https://makech-technology-879381274336.d.codeartifact.us-east-2.amazonaws.com/maven/makech-technology-maven-repository/")
            credentials {
                username = "aws"
                password = System.getenv("CODEARTIFACT_AUTH_TOKEN")
            }
        }
    }
}